### ISSUE TITLE
Cursor covering last letter.

### ISSUE THREAD

**Issue by arpio23** [cutie-shell/cutie-terminal#1]
The cursor is covering the last letter you typing. Its hard to correct mistyping when backspacing.

**Comment by arpio23** [comment]
This fixes it for me, but its not a real fix.
https://github.com/cutie-shell/cutie-terminal/tree/feature/trixie/testing

**Comment by erikinkinen** [comment]
> This fixes it for me, but its not a real fix. https://github.com/cutie-shell/cutie-terminal/tree/feature/trixie/testing

Huh, that's weird.

Anyways, I am quite positive this is not a bug in cutie-terminal per se, but rather a regression in qmltermwidget from our Qt6 port.
